export const t = (key: string, vars: Record<string, string | number> = {}) => {
  const value = messages[key] ?? key
  return Object.entries(vars).reduce(
    (result, [name, next]) => result.split(`{{${name}}}`).join(String(next)),
    value,
  )
}

export const messages: Record<string, string> = {
  "app.task-list": "Tasks",
  "app.add-task": "Add Task",
  "app.about": "About Motrix",
  "app.preferences": "Preferences...",
  "app.check-updates-now": "Check now",
  "app.checking-for-updates": "Checking for updates ...",
  "app.yes": "Yes",
  "app.no": "No",
  "app.save": "Save",
  "app.reset": "Discard",
  "app.cancel": "Cancel",
  "app.submit": "Submit",
  "app.gt1d": "> 1 day",
  "app.hour": "h",
  "app.minute": "m",
  "app.second": "s",
  "subnav.task-list": "Tasks",
  "subnav.preferences": "Preferences",
  "task.active": "Downloading",
  "task.waiting": "Waiting",
  "task.stopped": "Stopped",
  "task.new-task": "New Task",
  "task.uri-task": "URL",
  "task.torrent-task": "Torrent",
  "task.uri-task-tips": "One task url per line (supports magnet)",
  "task.thunder-link-tips": "Tip: Thunder links may not be downloadable after decoding",
  "task.new-task-uris-required": "Please enter at least one valid resource url",
  "task.new-task-torrent-required": "Please select a torrent file",
  "task.file-name": "Name",
  "task.file-extension": "Extension",
  "task.file-size": "Size",
  "task.file-completed-size": "Completed",
  "task.selected-files-sum": "Selected: {{selectedFilesCount}} files, total size {{selectedFilesTotalSize}}",
  "task.select-at-least-one": "Please select at least one file",
  "task.task-gid": "GID",
  "task.task-name": "Task Name",
  "task.task-out": "Rename",
  "task.task-out-tips": "Optional",
  "task.task-split": "Splits",
  "task.task-dir": "Save to",
  "task.task-user-agent": "User-Agent",
  "task.task-authorization": "Authorization",
  "task.task-referer": "Referer",
  "task.task-cookie": "Cookie",
  "task.task-proxy": "Proxy",
  "task.task-error-info": "Error",
  "task.task-piece-length": "Piece Size",
  "task.task-num-pieces": "Pieces",
  "task.task-bittorrent-info": "Torrent Info",
  "task.task-info-hash": "Hash",
  "task.task-bittorrent-creation-date": "Creation Date",
  "task.task-bittorrent-comment": "Comment",
  "task.task-progress-info": "Progress",
  "task.task-status": "Status",
  "task.task-num-seeders": "Seeders",
  "task.task-connections": "Connections",
  "task.task-download-speed": "Download Speed",
  "task.task-upload-speed": "Upload Speed",
  "task.task-upload-length": "Uploaded",
  "task.task-ratio": "Ratio",
  "task.task-peer-host": "Host",
  "task.task-peer-client": "Client",
  "task.navigate-to-downloading": "Navigate to Downloading",
  "task.show-advanced-options": "Advanced Options",
  "task.delete-selected-tasks": "Delete Selected Tasks",
  "task.delete-task": "Delete Task",
  "task.delete-task-confirm": "Are you sure you want to remove download task \"{{taskName}}\"?",
  "task.batch-delete-task-confirm": "Are you sure you want to remove {{count}} download tasks in batch?",
  "task.delete-task-label": "Delete with Files",
  "task.delete-task-success": "Successfully deleted task \"{{taskName}}\"",
  "task.delete-task-fail": "Failed to delete task \"{{taskName}}\"",
  "task.resume-task": "Resume Task",
  "task.resume-all-task": "Resume All Tasks",
  "task.resume-all-task-success": "Successfully resumed all tasks",
  "task.resume-all-task-fail": "Failed to resume all tasks",
  "task.pause-task": "Pause Task",
  "task.pause-all-task": "Pause All Tasks",
  "task.pause-all-task-success": "Successfully paused all tasks",
  "task.pause-all-task-fail": "Failed to pause all tasks",
  "task.purge-record": "Purge Task Record",
  "task.purge-record-success": "Successfully purged task records",
  "task.purge-record-fail": "Failed to purge task records",
  "task.refresh-list": "Refresh Task List",
  "task.no-task": "There are no current tasks",
  "task.copy-link": "Copy Link",
  "task.copy-link-success": "Successfully copied link",
  "task.remove-record": "Remove Task Record",
  "task.remove-record-confirm": "Are you sure you want to remove download record for \"{{taskName}}\"?",
  "task.remove-record-success": "Successfully removed task record for \"{{taskName}}\"",
  "task.remove-record-fail": "Failed to remove task record for \"{{taskName}}\"",
  "task.show-in-folder": "Show Task In Folder",
  "task.file-not-exist": "Target file does not exist or has been deleted",
  "task.file-path-error": "File path error",
  "task.opening-task-message": "Opening \"{{taskName}}\" ...",
  "task.get-task-name": "Getting task name...",
  "task.remaining-prefix": "Remaining",
  "task.select-torrent": "Drag torrent file here, or click to select",
  "task.task-detail-title": "Task Details",
  "task.download-start-message": "Started downloading {{taskName}}",
  "task.download-stop-message": "Stopped downloading {{taskName}}",
  "task.download-error-message": "Error occurred when downloading {{taskName}}",
  "task.download-complete-message": "Completed downloading {{taskName}}",
  "task.bt-download-complete-message": "Completed downloading {{taskName}}, seeding",
  "task.bt-download-complete-tips": "Tips: You can stop a task to end its seeding",
  "task.bt-stopping-seeding-tip": "Stopping seeding, it will take some time to disconnect, please wait patiently",
  "preferences.basic": "Basic",
  "preferences.advanced": "Advanced",
  "preferences.lab": "Lab",
  "preferences.save": "Save & Apply",
  "preferences.save-success-message": "Preferences saved successfully",
  "preferences.save-fail-message": "Preferences failed to save",
  "preferences.discard": "Discard",
  "preferences.startup": "Startup",
  "preferences.open-at-login": "Open at login",
  "preferences.keep-window-state": "Keep size and position of the window when exited",
  "preferences.auto-resume-all": "Automatically resume all unfinished tasks",
  "preferences.default-dir": "Default Path",
  "preferences.transfer-settings": "Transmission",
  "preferences.transfer-speed-upload": "Upload limit",
  "preferences.transfer-speed-download": "Download limit",
  "preferences.bt-settings": "BitTorrent",
  "preferences.bt-save-metadata": "Save magnet link as torrent file",
  "preferences.bt-auto-download-content": "Automatically download magnet and torrent content",
  "preferences.bt-force-encryption": "BT force encryption",
  "preferences.keep-seeding": "Keep seeding until manually stopped",
  "preferences.seed-ratio": "Seed Ratio",
  "preferences.seed-time": "Seed Time",
  "preferences.seed-time-unit": "minutes",
  "preferences.task-manage": "Task Management",
  "preferences.max-concurrent-downloads": "Maximum active tasks",
  "preferences.max-connection-per-server": "Maximum connections per server",
  "preferences.new-task-show-downloading": "Automatically show downloading after adding task",
  "preferences.no-confirm-before-delete-task": "No confirmation is required before deleting task",
  "preferences.continue": "Continue",
  "preferences.task-completed-notify": "Notify after download is complete",
  "preferences.appearance": "Appearance",
  "preferences.theme-auto": "Auto",
  "preferences.theme-light": "Light",
  "preferences.theme-dark": "Dark",
  "preferences.auto-hide-window": "Auto Hide Window",
  "preferences.run-mode": "Run As",
  "preferences.run-mode-standard": "Standard Application",
  "preferences.run-mode-tray": "Tray Application",
  "preferences.run-mode-hide-tray": "Hide Tray Application",
  "preferences.tray-speedometer": "Show the real-time speed in the menu bar tray",
  "preferences.show-progress-bar": "Show download progress bar",
  "preferences.language": "Language",
  "preferences.change-language": "Change language",
  "preferences.hide-app-menu": "Hide App Menu (Windows & Linux Only)",
  "preferences.proxy": "Proxy",
  "preferences.enable-proxy": "Enable Proxy",
  "preferences.proxy-bypass-input-tips": "Bypass proxy settings for these Hosts and Domains, one per line",
  "preferences.proxy-scope-download": "Download",
  "preferences.proxy-scope-update-app": "Update Application",
  "preferences.proxy-scope-update-trackers": "Update Trackers",
  "preferences.proxy-tips": "View Proxy Manual",
  "preferences.bt-tracker": "Tracker Servers",
  "preferences.bt-tracker-input-tips": "Tracker servers, one per line",
  "preferences.bt-tracker-tips": "Recommended: ",
  "preferences.sync-tracker-tips": "Sync",
  "preferences.auto-sync-tracker": "Update tracker list every day automatically",
  "preferences.port": "Listen Ports",
  "preferences.bt-port": "BT Listen Port",
  "preferences.dht-port": "DHT Listen Port",
  "preferences.rpc": "RPC",
  "preferences.rpc-listen-port": "RPC Listen Port",
  "preferences.rpc-secret": "RPC Secret",
  "preferences.rpc-secret-tips": "View RPC Secret Manual",
  "preferences.developer": "Developer",
  "preferences.user-agent": "User-Agent",
  "preferences.mock-user-agent": "Mock User-Agent",
  "preferences.aria2-conf-path": "Built-in aria2.conf path",
  "preferences.app-log-path": "App log path",
  "preferences.download-session-path": "Download session path",
  "preferences.session-reset": "Reset download session",
  "preferences.session-reset-confirm": "Are you sure you want to reset download session?",
  "preferences.factory-reset": "Factory Reset",
  "preferences.factory-reset-confirm": "Are you sure you want to revert to factory settings?",
  "preferences.lab-warning": "Enabling lab features may result in app crash or data loss, decide at you own risk!",
  "preferences.download-protocol": "Protocols",
  "preferences.protocols-default-client": "Set as the default client for the following protocols",
  "preferences.protocols-magnet": "Magnet [ magnet:// ]",
  "preferences.protocols-thunder": "Thunder [ thunder:// ]",
  "preferences.auto-update": "Auto Update",
  "preferences.auto-check-update": "Automatically check for updates",
  "preferences.last-check-update-time": "Last checked for an update",
  "preferences.not-saved": "Preferences not saved",
  "preferences.not-saved-confirm": "The modified preferences will be lost, are you sure you want to leave?",
  "about.engine-version": "Engine Version",
  "about.license": "License",
  "about.about": "About",
  "about.release": "Releases",
  "about.support": "Support",
}
